### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [2]:
np.version.version

'1.16.2'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [61]:
a = np.arange(1, 60, 2).reshape(2, 3, 5)

In [86]:
a = np.random.rand(2, 3, 5)

### 4. Print a.

In [87]:
print(a)

[[[0.57922109 0.99111134 0.1179264  0.91765455 0.20302295]
  [0.94530191 0.31769842 0.53878365 0.57583669 0.70951397]
  [0.39629769 0.4592317  0.03029252 0.26538418 0.07369177]]

 [[0.43379614 0.74822219 0.42350579 0.64640051 0.41401605]
  [0.9534493  0.43966744 0.55547213 0.50026785 0.09296537]
  [0.43319302 0.28032089 0.12039818 0.83203468 0.69900886]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [88]:
b = np.ones((5,2,3))

### 6. Print b.

In [89]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [90]:
print('b.shape: ', b.shape)    # imprime o formato da array
print('b.size: ', b.size)      # imprime o tamanho da array
print('b.dtype: ', b.dtype) 

b.shape:  (5, 2, 3)
b.size:  30
b.dtype:  float64


In [91]:
print('a.shape: ', a.shape)    # imprime o formato da array
print('a.size: ', a.size)      # imprime o tamanho da array
print('a.dtype: ', a.dtype) 

a.shape:  (2, 3, 5)
a.size:  30
a.dtype:  float64


### 8. Are you able to add a and b? Why or why not?

In [92]:
""""
Não, porque para operações de adição, 
subtração, divisão e multiplicação é 
necessário que as arrays possuam o mesmo shape
"""

'"\nNão, porque para operações de adição, \nsubtração, divisão e multiplicação é \nnecessário que as arrays possuam o mesmo shape\n'

In [93]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [94]:
c = b.reshape((2, 3, 5))

### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [95]:
d = a + c

In [96]:
""""
Porque nessa operação ambas as arrays envolvidas na adição possuem o mesmo shape
"""

'"\nPorque nessa operação ambas as arrays envolvidas na adição possuem o mesmo shape\n'

### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [97]:
print(a)

[[[0.57922109 0.99111134 0.1179264  0.91765455 0.20302295]
  [0.94530191 0.31769842 0.53878365 0.57583669 0.70951397]
  [0.39629769 0.4592317  0.03029252 0.26538418 0.07369177]]

 [[0.43379614 0.74822219 0.42350579 0.64640051 0.41401605]
  [0.9534493  0.43966744 0.55547213 0.50026785 0.09296537]
  [0.43319302 0.28032089 0.12039818 0.83203468 0.69900886]]]


In [98]:
print(d)

[[[1.57922109 1.99111134 1.1179264  1.91765455 1.20302295]
  [1.94530191 1.31769842 1.53878365 1.57583669 1.70951397]
  [1.39629769 1.4592317  1.03029252 1.26538418 1.07369177]]

 [[1.43379614 1.74822219 1.42350579 1.64640051 1.41401605]
  [1.9534493  1.43966744 1.55547213 1.50026785 1.09296537]
  [1.43319302 1.28032089 1.12039818 1.83203468 1.69900886]]]


In [99]:
""""
A matriz 'c' é uma matriz unitária (composta apenas pelo numero um) e por isso a matriz D 
é exatamente o valor da matriz a com a adição de uma unidade em cada um de seu valor
"""

'"\nA matriz \'c\' é uma matriz unitária (composta apenas pelo numero um) e por isso a matriz D \né exatamente o valor da matriz a com a adição de uma unidade em cada um de seu valor\n'

### 12. Multiply a and c. Assign the result to e.

In [100]:
e = a*c

In [101]:
print(e)

[[[0.57922109 0.99111134 0.1179264  0.91765455 0.20302295]
  [0.94530191 0.31769842 0.53878365 0.57583669 0.70951397]
  [0.39629769 0.4592317  0.03029252 0.26538418 0.07369177]]

 [[0.43379614 0.74822219 0.42350579 0.64640051 0.41401605]
  [0.9534493  0.43966744 0.55547213 0.50026785 0.09296537]
  [0.43319302 0.28032089 0.12039818 0.83203468 0.69900886]]]


### 13. Does e equal to a? Why or why not?

In [102]:
""""
Sim, pois a matriz 'c' é uma matriz unitária (composta apenas pelo numero um) e por isso na
multiplicação ela não altera o resultado final.
"""

'"\nSim, pois a matriz \'c\' é uma matriz unitária (composta apenas pelo numero um) e por isso na\nmultiplicação ela não altera o resultado final.\n'

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [103]:
d_max = d.max()
d_max

1.9911113376536198

In [104]:
d_min = d.min()
d_min

1.0302925207901144

In [105]:
d_mean = d.mean()
d_mean

1.4897895739110645

### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [127]:
# First create an empty array "f" with the same shape (i.e. 2x3x5) as d using np.empty
f = np.empty([2,3,5])
f

array([[[ 75., 100.,  25.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,   0.,  25.,  25.]],

       [[ 25.,  75.,  25.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  75.,  75.]]])


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [107]:
# d: shape (2,3,5)

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100
            else:
                f[i,j,k] = 25
                

In [108]:
print(f)

[[[ 75. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.   0.  25.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  75.]]]


### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [109]:
print(d)

[[[1.57922109 1.99111134 1.1179264  1.91765455 1.20302295]
  [1.94530191 1.31769842 1.53878365 1.57583669 1.70951397]
  [1.39629769 1.4592317  1.03029252 1.26538418 1.07369177]]

 [[1.43379614 1.74822219 1.42350579 1.64640051 1.41401605]
  [1.9534493  1.43966744 1.55547213 1.50026785 1.09296537]
  [1.43319302 1.28032089 1.12039818 1.83203468 1.69900886]]]


In [110]:
print(f)

[[[ 75. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.   0.  25.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


In [128]:
f = np.array2string(f)

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = "D"
            elif d[i,j,k] == d_mean:
                f[i,j,k] = "C"
            elif d[i,j,k] == d_min:
                f[i,j,k] = "A"
            elif d[i,j,k] == d_max:
                f[i,j,k] = "E"
            else:
                f[i,j,k] = "B"

TypeError: 'str' object does not support item assignment

In [126]:
print(f)

[[['D' 'E' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'A' 'B' 'B']]

 [['B' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'D' 'D']]]
